### ISSUE TITLE
can this code run on linux?

### ISSUE THREAD

**Issue by ynuwm** [Illuminati91/pycocoevalcap#1]
I run this code normally on my win10 computer, but it occurs this problem when it runs on Linux server:
No such file or directory: 'java' : 'java'.
so, I want to know if this code can run on linux when I configure the Java environment on Linux?

**Comment by sks3i** [comment]
I haven't tested on Linux yet. I'll give it a shot today/tomorrow and then update you.

**Comment by ynuwm** [comment]
Thank you, waiting for your good news, I will also try it.

**Comment by sks3i** [comment]
@ynuwm if you setup java, you should be able to run the code on linux.

**Comment by ynuwm** [comment]
Thank you. I have run it.
